import { StyleSheet, Dimensions } from 'react-native';
const { width, height } = Dimensions.get('window');

export default {
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
    position: 'relative',
  },
  navigationText: {
    fontFamily: 'calibri',
    fontSize: 20,
    color: '#fff',
  },
  w20: {
    width: 20,
  },
  headerWrapper: {
    backgroundColor: 'blue',
    height: 50,
    lineHeight: 50,
    paddingLeft: 20,
    flexDirection: 'row',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  headerText: {
    textTransform: 'uppercase',
    fontFamily: 'calibri',
    fontSize: 20,
    textAlign: 'left',
    color: '#FFFFFF',
  },
  teamContainer: {
    paddingTop: 10,
    paddingBottom: 10,
  },
  avatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    marginRight: 10,
  },
  itemView: {
    paddingLeft: 15,
    paddingRight: 15,
    paddingTop: 10,
    paddingBottom: 10,
    flexDirection: 'row',
  },
  infoView: {
    alignItems: 'flex-start',
    marginLeft: 10,
    justifyContent: 'center',
    flex: 1.5,
  },
  username: {
    fontFamily: 'calibri',
    fontSize: 15,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  infoText: {
    fontFamily: 'calibri',
    fontSize: 12,
    textAlign: 'center',
    fontStyle: 'italic',
    color: '#AAAAAA',
  },
  signView: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  signButton: {
    backgroundColor: 'blue',
    borderRadius: 20,
    padding: 5,
    marginBottom: 5,
    width: 80,
  },
  signButtonText: {
    fontFamily: 'calibri',
    fontSize: 15,
    textAlign: 'center',
    fontStyle: 'italic',
    color: '#ffffff',
  },
  timerText: {
    fontFamily: 'calibri',
    fontSize: 10,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  playButton: {
    backgroundColor: 'red',
    borderRadius: 20,
    padding: 5,
    marginBottom: 5,
    width: 80,
  },
  playButtonText: {
    fontFamily: 'calibri',
    fontSize: 13,
    textAlign: 'center',
    fontStyle: 'italic',
    color: '#ffffff',
  },
  numberText: {
    fontFamily: 'calibri',
    fontSize: 20,
    textAlign: 'center',
    fontStyle: 'italic',
    color: '#0000ff',
  },
  bgWhite: {
    backgroundColor: '#fff',
  },
  disabledTab: {
    fontFamily: 'calibri-italic',
  },
  activeTab: {
    fontFamily: 'calibri-italic',
    color: '#0071c0',
  },
  labelText: {
    color: '#0071c0',
    fontFamily: 'calibri-italic',
  },
  bgBlue: {
    backgroundColor: '#0071c0',
  },
  flexCenterColumn: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
  },
  footerModal: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
  },
  footerButtonModal: {
    backgroundColor: '#0070C1',
    color: '#fff',
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    paddingTop: 16,
    paddingBottom: 16,
  },
  footerButtonModal2: {
    color: '#919192',
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    paddingTop: 16,
    paddingBottom: 16,
    marginBottom: 10,
  }, 
  bottomMainButtonTextModal: {
    color: '#fff',
    fontSize: 18,
    fontFamily: 'calibri',
    textAlign: 'center',
  },
  modal: {
    alignItems: 'center',
    width: width - 20,
    height: 400,
  },
  modalView: {
    marginTop: 10,
  },
  modalViewImage: {
    width: '100%',
    flexDirection: 'row',
  },
  modalImage: {
    width: 100, height: 100, borderRadius: 100,
  },
  modalTitle: {
    fontFamily: 'calibri-italic',
    color: '#747474',
    fontSize: 15,
    textAlign: 'center',
  },
  modalName: {
    fontFamily: 'calibri-italic',
    color: '#000',
    fontSize: 15,
    textAlign: 'center',
  },
  modalUsername: {
    fontFamily: 'calibri-italic',
    color: 'rgba(0,0,0,.3)',
    fontSize: 11,
    textAlign: 'center',
  },
  modalMessage: {
    fontFamily: 'calibri-italic',
    color: 'rgba(0,0,0,.3)',
    fontSize: 11,
    textAlign: 'center',
  },
};
