export default {
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,.9)',
    display: 'flex',
  },
  contentContainer: {
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  backgroundImageStyle: {
    resizeMode: 'cover',
  },
  buttonContainer: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  itemUsername: {
    marginBottom: 30,
  },
  marginTop20: {
    marginTop: 20,
  },
  marginTop40: {
    marginTop: 40,
  },
  submitButton: {
    backgroundColor: 'transparent',
    borderColor: '#fff',
    borderStyle: 'solid',
    borderWidth: 1,
    paddingTop: 13,
    paddingBottom: 10,
    borderRadius: 41,
    marginLeft: 25,
    marginRight: 25,
    width: 270,
  },
  submitButtonText: {
    color: '#fff',
    fontFamily: 'calibri',
    fontSize: 23,
    textAlign: 'center',
  },
  subheadingWelcome: {
    fontFamily: 'calibri',
    fontSize: 16,
    color: '#fff',
  },
  backgroundImageSize: {
    width: '100%',
    height: '100%',
  },
  flexContainer: {
    marginLeft: 25,
    marginRight: 25,
    flex: 1,
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  icon: {
    color: '#fff',
  },
  footerContainer: {
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    paddingBottom: 30,
  },
  logo: {
    flex: 1,
    height: 130,
    width: 130,
  },
  logoWelcome: {
    marginTop: 30,
    flex: 1,
    height: 130,
    width: 130,
  },
  headerContainer: {
    flex: 1,
  },
  backgroundImage: {
    flex: 1,
    resizeMode: 'cover',
  },
  footerChildContainer: {
    position: 'absolute',
    bottom: 17,
    right: 38,
  },
  input: {
    color: '#fff',
    fontFamily: 'calibri',
    fontSize: 20,
    borderColor: '#fff',
  },
  inputLabel: {
    color: 'rgba(255,255,255,.3)',
    fontFamily: 'calibri-italic',
    fontSize: 19,
    flex: 1,
  },
  subeading2Login: {
    fontFamily: 'calibri',
    color: '#fff',
    fontSize: 18,
    paddingTop: 30,
  },
  loginLink: {
    fontFamily: 'calibri',
    color: '#0172c1',
    fontSize: 18,
    paddingTop: 30,
    paddingBottom: 50,
  },
  forgotPasswordContainer: {
    display: 'flex',
    justifyContent: 'flex-start',
    flexDirection: 'row',
    alignItems: 'flex-start',
    textAlign: 'left',
  },
  forgotPassword: {
    color: '#0172c1',
    textDecorationLine: 'underline',
    fontFamily: 'calibri-italic',
    fontSize: 17,
    textAlign: 'left',
    marginTop: 30,
  },
};
